DATE: 6/15/16 
SUBJECT: Test Message from Igtampe 
- 
Hello my fellow subjects! It is I, Igtampe. I come forth to speak to you about  Igtampe DOS's New, inovative MSGBOARD system! This message system will allow me to send you all a hearty hello in the event that something big happens, like an important fix to the updator, as was necessary to update from beta build 6003 to 6006 in the NT 9.0 Beta program. In any case, Welcome to the MSGBOARD system! 
- 
Have a lovely day! 
Igtampe 
