DATE: Tue 06/28/2016
SUBJECT: Second Test Message
 
Hello Igtampe DOS users! This second test message is here to test MessageGen, a new program based on Infinity Text version 1.1. MessageGen is an internal       program used for writing messages.  
 
As you may have noticed, this message has no hyphens in between lines. The      hyphen was originally implemented to save space on the code, and not write the  same line again. This was a simple fix at the time. Now, It's been 2 years and apropper blank line was necessary. In any case, you can test the new build of    Infinity Text on Igtampe DOS NT Beta 6008 and later. 
 
Have a lovely day! 
Igtampe 
